version: '3'

services:
  db:
    image: mariadb:10.4
    container_name: "laravel-ec-mariaDB"
    volumes:
      - ./data:/var/lib/mysql
      - ./db/my.cnf://etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
      - "13306:3306"
  php-apache:
    build: ./php
    container_name: "laravel-ec-php"
    volumes:
      - ./source:/var/www/html
      - ./php/vhost.conf:/etc/apache2/conf-enabled/vhost.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: "laravel-ec-phpmyadmin"
    depends_on:
      - db
    ports:
      - "3000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=docker
      - PMA_PASSWORD=docker
